[package]
name = "s1-movie-review"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "1.4.0"
solana-program = "1.18.9"
thiserror = "1.0.58"

[lib]
crate-type = ["cdylib", "lib"]
